### ISSUE TITLE
it works great, thanks

### ISSUE THREAD

**Issue by dpnolte** [joschi127/doctrine-entity-override-bundle#5] opened 2016-12-23 12:58 UTC
One issue that I've come across:

When running 'php bin/console doctrine:generate:entities':
`php.CRITICAL: Fatal Error: Call to a member function getProperty() on a non-object {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to a member function getProperty() on a non-object at [..]/vendor/joschi127/doctrine-entity-override-bundle/EventListener/LoadORMMetadataSubscriber.php:303)"}` 

It works again when I add an if statement that checks whether reflectionclass is null in LoadORMMetadataSubscriber.php at line 303:
`foreach ($metadata->fieldMappings as $name => $mapping) {
                if (!isset($mapping['declared'])) { // only if not already set
                	if($metadata->getReflectionClass() !== null) {
	                    if (!$metadata->getReflectionClass()->getProperty($name)->isPrivate()) {
	                        $metadata->fieldMappings[$mapping['fieldName']]['declared'] = $metadata->getName();
	                        $metadata->fieldMappings[$mapping['fieldName']]['inherited'] = $metadata->getName();
	                    }
                	}
                }
            }`

**Comment by joschi127** [comment] 2016-12-26 16:48
Hi, and thanks very much for your feedback.

I cannot reproduce your error. Do you think you can provide some example code or submit a pull request with an added test which is failing and showing what's going wrong?

Tried to reproduce, but $metadata->getReflectionClass() is never null for me, also when running 'doctrine:generate:entities' it is always set.

**Comment by joschi127** [comment] 2018-03-09 17:25
no answer anymore, cannot reproduce - so closing this one now

**Closed as completed by joschi127** 2018-03-09 17:25 UTC
